# Variables
@baseUrl = http://localhost:3333

# Health check
GET {{baseUrl}}/health

###

# Get Rooms
GET {{baseUrl}}/rooms

###

# Create Room 
POST {{baseUrl}}/rooms
Content-Type: application/json

{ 
  "name": "Example room",
  "description": "This is an example room"
}